name: Build Windows Executable
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Update version and run pyinstaller
        run: |
          .\.github\update_version.ps1
          python -m PyInstaller ui.spec
      - name: Prepare release directory
        run: |
          $latestTag = git describe --tags --abbrev=0
          $bmsPathName = "bms-translator-" + $latestTag
          Write-Output $latestTag  $bmsPathName
          mkdir -p $bmsPathName
          cp -r config/ $bmsPathName/config/
          cp dist/ui.exe $bmsPathName/$bmsPathName.exe
      - name: Create archive zip
        run: Compress-Archive -Path "$bmsPathName" -DestinationPath "$bmsPathName.zip"
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            ./bms-translator.zip